import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import ConnectWithGithub from '../ConnectWithGithub'
import GithubCard from '../GithubCard'
import styles from '../styles/Home.module.css'

export default class Home extends React.Component {
  constructor(props) {
    super()

    this.state = {
      ready: false,
      userData: null
    }
  }


  componentDidMount() {
    this.getUSerData()
  }


  getUSerData = async () => {
    const res = await fetch('/api/whoami')
    const json = await res.json()
    console.log(json);
    this.setState({ userData: json.data, ready: true })
  }


  render() {


    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.fixedLink}><a href='https://github.com/jonathanlurie/nextgithublogin'>See on GitHub</a> - made by <a href='https://twitter.com/jonathanlurie'>@jonathanlurie</a></div>
        { this.state.userData ? <GithubCard githubData={this.state.userData}/> : <ConnectWithGithub/> }
      </div>
    )
  }
}